version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8081:8081"
    # Only map testdata if needed
    volumes:
      - ./backend/testdata:/root/testdata

  websocket:
    build:
      context: ./websocket-server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend/devsyncpro-ui
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - websocket
    develop:
      watch:
        - action: sync
          path: ./frontend/devsyncpro-ui/src
          target: /app/src
