services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"

  websocket:
    build: ./websocket-server
    ports:
      - "8081:8081"
      - "9000:9000"
    depends_on:
      - backend

  frontend:
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./frontend/devsyncpro-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/devsyncpro-ui:/app
      - /app/node_modules
    develop:
      watch:
        - action: sync
          path: ./frontend/devsyncpro-ui
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/devsyncpro-ui/package.json
    depends_on:
      - backend
      - websocket
